---

- name: Install openscap
  ansible.builtin.dnf:
    state: present
    name:
      - openscap-scanner
      - scap-security-guide

- name: Run CIS oscap scan and create ~/report.html
  ansible.builtin.command:
    oscap xccdf eval --profile cis \
      --report ~/report.html \
      --cpe /usr/share/xml/scap/ssg/content/ssg-almalinux8-cpe-dictionary.xml \
      /usr/share/xml/scap/ssg/content/ssg-almalinux8-xccdf.xml
  changed_when: true
  no_log: false
  register: scan_return
  failed_when: scan_return.stdout is not defined
